// DO NOT EDIT THIS FILE
// This file is automatically generated from the webgme-setup-tool.
'use strict';


var config = require('webgme/config/config.default'),
    validateConfig = require('webgme/config/validator');

// The paths can be loaded from the webgme-setup.json
config.plugin.basePaths.push(__dirname + '/../src/plugins');
config.visualization.decoratorPaths.push(__dirname + '/../src/decorators');
config.seedProjects.basePaths.push(__dirname + '/../src/seeds/PetriNet');



config.visualization.panelPaths.push(__dirname + '/../node_modules/webgme-composite-viz/src/visualizers/panels');




// Visualizer descriptors
config.visualization.visualizerDescriptors.push(__dirname + '/../src/visualizers/Visualizers.json');
// Add requirejs paths
config.requirejsPaths = {
  'CompositeViz': 'panels/CompositeViz/CompositeVizPanel',
  'panels': './src/visualizers/panels',
  'widgets': './src/visualizers/widgets',
  'panels/CompositeViz': './node_modules/webgme-composite-viz/src/visualizers/panels/CompositeViz',
  'widgets/CompositeViz': './node_modules/webgme-composite-viz/src/visualizers/widgets/CompositeViz',
  'webgme-composite-viz': './node_modules/webgme-composite-viz/src/common',
  'petri-net': './src/common'
};


config.mongo.uri = 'mongodb://127.0.0.1:27017/petri_net';
validateConfig(config);
module.exports = config;
